Update blank_template.py to fix Attribute Error
Previous configuration would give a :
...
.venv/lib/python3.12/site-packages/reflex/__init__.py", line 231, in __getattr__
    raise AttributeError(f"module 'reflex' has no attribute {name}") from None
AttributeError: module 'reflex' has no attribute reflex.color_mode_button

Also, "spacing" (line 36) would not accept anything but an integer for a value. It has been updated to 1 in this commit vs .5em in the previous one.



Updated